export const CREATE_PROFILE = "CREATE_PROFILE"
export const AUTH = "AUTH"
export const LOAD_USER = "LOAD_USER"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_SELECTION = "UPDATE_SELECTION"